# Generated by Django 3.2.7 on 2021-09-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210921_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='mainuser',
            name='u_t',
            field=models.CharField(choices=[(1, 'customer'), (2, 'seller')], default=1, max_length=50),
        ),
    ]
